import Head from 'next/head'
// import Link from 'next/Link'
import styles from 'styles/Home.module.css'
import Footer from 'src/components/Footer'
import Main from 'src/components/Main'
import Header from 'src/components/Header'
import { useCallback, useEffect,useState } from 'react'


export default function Home() {
  const [count, setCount] = useState(1)

  const handleClick = (e) => {
    setCount((count) => count + 1)
  }

  useEffect(() => {
    document.body.style.backgroundColor = "lightblue"
    return () => {
      document.body.style.backgroundColor = ""
    }
  },[])

  return (
    <div className={styles.container}>
      <Head>
        <title>Index page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <h1 className={styles.topAreaUI}>{count}</h1>
        <button onClick={ handleClick } className={styles.topAreaUI}>
          ボタン
        </button>
      <Main page="index"/>
      <Footer />
    </div>
  )
}
