import Head from 'next/head'
// import Link from 'next/Link'
import styles from 'styles/Home.module.css'
import Footer from 'src/components/Footer'
import Main from 'src/components/Main'
import Header from 'src/components/Header'
import { useCallback, useEffect, useState } from 'react'


export default function Home() {
  const [count, setCount] = useState(1)
  const [text, setText] = useState("")
  const [isShow, setIsShow] = useState(true)

  const handleClick = useCallback(() => {
    console.log(count);
    if (count < 10){
      setCount((count) => count + 1)
    }
  },[count])

  useEffect(() => {
    document.body.style.backgroundColor = "lightblue"
    return () => {
      document.body.style.backgroundColor = ""
    }
  },[])

const handleChange = useCallback((e) => {
  if(e.target.value.length > 5){
    alert("５文字以内にしてください")
    return
  }
  setText(e.target.value.trim())
}, [])

const handleDisplay = useCallback(() => {
  setIsShow((isShow) => !isShow)
}, [])

  return (
    <div className={styles.container}>
      <Head>
        <title>Index page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <div className={styles.containerTopArea}>
        {isShow ? <h1>{count}</h1> : null}
          <button
            onClick={ handleClick }
          >
            ボタン
          </button>
          <button
            onClick={ handleDisplay }
          >
            {isShow ? "非表示" : "表示"}
          </button>
          <input type="text" value={text} onChange={ handleChange }
          />
      </div>
      <Main page="index"/>
      <Footer />
    </div>
  )
}
